# Generated by Django 3.0.4 on 2021-02-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210222_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductKey',
        ),
    ]
