# Generated by Django 3.0.4 on 2021-02-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_productkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverkey',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
