# Generated by Django 3.0.4 on 2021-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkey',
            name='config_key',
            field=models.CharField(default='nithinCK', max_length=128),
        ),
    ]
