# Generated by Django 3.0.4 on 2021-03-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productkey_config_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkey',
            name='config_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='productkey',
            name='key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='serverkey',
            name='key',
            field=models.CharField(max_length=128),
        ),
    ]
