# Generated by Django 3.0.4 on 2020-08-13 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
                ('bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=16)),
                ('liters_per_unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed', models.IntegerField(default=0)),
                ('request', models.IntegerField(default=0)),
                ('key', models.CharField(max_length=128)),
                ('not_finished', models.BooleanField(default=True)),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPostPaidTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_units', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('post_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.PostPaid')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Rate')),
                ('units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='WaterDispenseFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('finished_on', models.DateTimeField(auto_now=True)),
                ('num_liters', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('transation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.WaterPostPaidTransaction')),
            ],
        ),
        migrations.CreateModel(
            name='WaterDispensedPeriodic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_at', models.IntegerField()),
                ('count', models.IntegerField()),
                ('transation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.WaterPostPaidTransaction')),
            ],
        ),
    ]
