# Generated by Django 3.0.4 on 2021-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watertransaction',
            name='not_finished',
        ),
        migrations.AddField(
            model_name='watertransaction',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
