# Generated by Django 3.0.4 on 2021-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210219_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertransaction',
            name='dispensed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='watertransaction',
            name='request',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
