# Generated by Django 3.0.4 on 2021-03-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210311_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertransaction',
            name='wait',
            field=models.IntegerField(default=10),
        ),
    ]
